export { Hero } from './Hero'
export { Features } from './Features'
export { CTA } from './CTA'
export { Contact } from './Contact'
export { Stats } from './Stats'
export { Testimonials } from './Testimonials'
